In [6]:
import numpy as np
array = np.array([1, 2])
array.tolist()
print(array)

[1 2]


In [12]:
import numpy as np
  
n_array = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Numpy is:")
print(n_array)
  
trace = np.trace(n_array)
  
  
print("Trace is:")
print(trace)

Numpy is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace is:
15


In [14]:
a= np.array([[1,2,6],[3,5,7]])
x=2
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i][j] > x:
            print(a[i][j] ,"is higher than", x)

6 is higher than 2
3 is higher than 2
5 is higher than 2
7 is higher than 2


In [15]:
my_array1= np.array([[1,2,3],[4,5,6],[7,8,9]])
my_array2= np.array([[7,8,9],[1,2,3],[4,5,6]])
s=my_array1+my_array2
s

array([[ 8, 10, 12],
       [ 5,  7,  9],
       [11, 13, 15]])

In [17]:
tab=np.array([[1,2,3],[0,1,1],[1,2,2]])
m=np.mean(tab,axis=1)
m          

array([2.        , 0.66666667, 1.66666667])